import { mkH } from '../utils/history';

export const INIT_TICKETS = [
  {
    id: 'TK-1041',
    title: 'VPN client crashing on Windows 11 update',
    requester: 'María García',
    requesterEmail: 'm.garcia@equilybrio.com',
    assignee: 'Camilo Reyes',
    queue: 'it',
    dept: 'IT',
    category: 'Infraestructura',
    status: 'open',
    priority: 'urgent',
    created: '2026-04-29T08:14',
    updated: '2026-04-29T09:45',
    tags: ['vpn', 'windows', 'crash'],
    slaDeadline: '2026-04-29T12:14',
    history: [
      mkH('created', '', 'open', 'Ticket abierto por solicitud de usuario.', 'Diagnóstico', 'Sistema', '2026-04-29T08:14'),
      mkH('status_change', 'new', 'open', 'Ticket tomado — revisando conflicto con KB5034763.', 'Diagnóstico', 'Camilo Reyes', '2026-04-29T08:32'),
      mkH('comment', '', '', 'Cliente confirma GlobalProtect 6.2.1. Error: authentication gateway unreachable.', 'Información adicional', 'Camilo Reyes', '2026-04-29T08:41'),
      mkH('comment', '', '', 'Conflicto confirmado. Solución: revertir KB5034763. Instrucciones enviadas.', 'Diagnóstico', 'Camilo Reyes', '2026-04-29T09:45'),
    ],
  },
  {
    id: 'TK-1040',
    title: 'Solicitar acceso a Power BI Premium',
    requester: 'Sofía Martínez',
    requesterEmail: 's.martinez@equilybrio.com',
    assignee: 'Luis Herrera',
    queue: 'analytics',
    dept: 'Analytics',
    category: 'Acceso Software',
    status: 'pending',
    priority: 'medium',
    created: '2026-04-28T15:30',
    updated: '2026-04-29T07:20',
    tags: ['power-bi', 'licencia'],
    slaDeadline: '2026-04-30T15:30',
    history: [
      mkH('created', '', 'new', 'Solicitud licencia Power BI Premium para proyecto Q2.', 'Diagnóstico', 'Sistema', '2026-04-28T15:30'),
      mkH('status_change', 'new', 'pending', 'Esperando formulario de aprobación del manager.', 'Seguimiento', 'Luis Herrera', '2026-04-28T16:10'),
    ],
  },
  {
    id: 'TK-1039',
    title: 'Error 500 en módulo de facturación',
    requester: 'Carlos Peña',
    requesterEmail: 'c.pena@equilybrio.com',
    assignee: 'Ana Ríos',
    queue: 'dev',
    dept: 'Dev',
    category: 'Bug',
    status: 'open',
    priority: 'high',
    created: '2026-04-28T11:00',
    updated: '2026-04-28T14:30',
    tags: ['bug', 'billing', 'producción'],
    slaDeadline: '2026-04-29T11:00',
    history: [
      mkH('created', '', 'open', 'Error 500 al generar facturas >50 líneas.', 'Diagnóstico', 'Sistema', '2026-04-28T11:00'),
      mkH('comment', '', '', 'Timeout en query de consolidación. Branch hotfix abierto.', 'Diagnóstico', 'Ana Ríos', '2026-04-28T11:45'),
      mkH('comment', '', '', 'Fix en staging. Deploy a producción en ~1h.', 'Seguimiento', 'Ana Ríos', '2026-04-28T14:30'),
    ],
  },
  {
    id: 'TK-1038',
    title: 'Laptop pantalla negra — ThinkPad X1 Carbon',
    requester: 'Diego Vargas',
    requesterEmail: 'd.vargas@equilybrio.com',
    assignee: 'Sin asignar',
    queue: 'it',
    dept: 'IT',
    category: 'Hardware',
    status: 'new',
    priority: 'high',
    created: '2026-04-29T10:02',
    updated: '2026-04-29T10:02',
    tags: ['hardware', 'laptop'],
    slaDeadline: '2026-04-29T14:02',
    history: [
      mkH('created', '', 'new', '#EQ-1137 no enciende. Pantalla negra con batería cargada.', 'Diagnóstico', 'Sistema', '2026-04-29T10:02'),
    ],
  },
  {
    id: 'TK-1037',
    title: 'Configurar SSO Okta — tenant Acme Corp',
    requester: 'Patricia Lara',
    requesterEmail: 'p.lara@equilybrio.com',
    assignee: 'Camilo Reyes',
    queue: 'security',
    dept: 'Security',
    category: 'Identidad',
    status: 'resolved',
    priority: 'medium',
    created: '2026-04-25T09:00',
    updated: '2026-04-28T16:00',
    tags: ['sso', 'okta'],
    slaDeadline: '2026-04-28T09:00',
    history: [
      mkH('created', '', 'open', 'SSO Okta para Acme Corp. Contrato firmado, deadline 3 días.', 'Diagnóstico', 'Sistema', '2026-04-25T09:00'),
      mkH('queue_move', 'it', 'security', 'Movido a Seguridad — tarea de identidad empresarial.', 'Reasignación', 'Camilo Reyes', '2026-04-25T09:30'),
      mkH('status_change', 'open', 'resolved', 'SSO activo y verificado. Documentación enviada.', 'Resolución', 'Camilo Reyes', '2026-04-28T16:00'),
    ],
  },
  {
    id: 'TK-1036',
    title: 'Reporte de gastos Q1 no genera PDF',
    requester: 'Elena Torres',
    requesterEmail: 'e.torres@equilybrio.com',
    assignee: 'Luis Herrera',
    queue: 'finance',
    dept: 'Finance',
    category: 'Bug',
    status: 'closed',
    priority: 'low',
    created: '2026-04-22T14:00',
    updated: '2026-04-24T11:00',
    tags: ['finanzas', 'pdf'],
    slaDeadline: '2026-04-25T14:00',
    history: [
      mkH('created', '', 'new', 'Botón Exportar PDF no responde.', 'Diagnóstico', 'Sistema', '2026-04-22T14:00'),
      mkH('comment', '', '', 'Bloqueo de popups en Chrome. Instrucciones enviadas.', 'Resolución', 'Luis Herrera', '2026-04-22T15:30'),
      mkH('status_change', 'open', 'closed', 'Usuario confirma que funciona.', 'Cierre', 'Luis Herrera', '2026-04-24T11:00'),
    ],
  },
  {
    id: 'TK-1035',
    title: 'Onboarding 3 ingenieros — inicio 5 mayo',
    requester: 'HR Equilybrio',
    requesterEmail: 'hr@equilybrio.com',
    assignee: 'Ana Ríos',
    queue: 'hr',
    dept: 'HR',
    category: 'Onboarding',
    status: 'open',
    priority: 'medium',
    created: '2026-04-27T08:00',
    updated: '2026-04-29T09:00',
    tags: ['hr', 'onboarding'],
    slaDeadline: '2026-04-30T08:00',
    history: [
      mkH('created', '', 'open', 'Javier Mora (BE), Laura Suárez (FE), Roberto Gil (DevOps).', 'Diagnóstico', 'Sistema', '2026-04-27T08:00'),
      mkH('queue_move', 'it', 'hr', 'Centralizado en RRHH para coordinación completa.', 'Reasignación', 'Ana Ríos', '2026-04-29T09:00'),
    ],
  },
  {
    id: 'TK-1034',
    title: 'Certificado SSL expirado — api.equilybrio.io',
    requester: 'Monitor Alerta',
    requesterEmail: 'alerts@equilybrio.com',
    assignee: 'Camilo Reyes',
    queue: 'devops',
    dept: 'DevOps',
    category: 'Seguridad',
    status: 'open',
    priority: 'urgent',
    created: '2026-04-29T03:00',
    updated: '2026-04-29T03:15',
    tags: ['ssl', 'api'],
    slaDeadline: '2026-04-29T09:00',
    history: [
      mkH('created', '', 'open', 'ALERTA: Cert SSL api.equilybrio.io expira en <6h.', 'Escalado', 'Sistema', '2026-04-29T03:00'),
      mkH('status_change', 'new', 'open', "Iniciando renovación Let's Encrypt.", 'Diagnóstico', 'Camilo Reyes', '2026-04-29T03:15'),
    ],
  },
];
